---
FQDN: localvm1.localdomain
STORAGE_DOMAIN_ADDR: shablul.eng.lab.tlv.redhat.com
STORAGE_DOMAIN_PATH: /exports/multipass/export/images/rnd/etokar/sansa/he
VM_MAC_ADDR: 00:16:3e:1e:15:d7
CLOUD_INIT_DOMAIN_NAME: localdomain
CLOUD_INIT_HOST_NAME: localvm1
HOST_NAME: sansa
HOST_ADDRESS: sansa.usersys.redhat.com
LOCAL_VM_DIR: /usr/localvm
ADMIN_PASSWORD: 1234
APPLIANCE_PASSWORD: qum5net
HOST_PASSWORD: qum5net
STORAGE_DOMAIN_NAME: he_storage
TIME_ZONE: Asia/Jerusalem
BRIDGE: ovirtmgmt
VM_NAME: HostedEngine
MEM_SIZE: 2048
CONSOLE_TYPE: vnc
SP_UUID: 00000000-0000-0000-0000-000000000000
CDROM_UUID:
CDROM:
NIC_UUID: 45645645
CONSOLE_UUID:
VIDEO_DEVICE: vga
GRAPHICS_DEVICE: vnc
VCPUS: 4
MAXVCPUS: 4
CPU_SOCKETS: 2
CPU_TYPE: Conroe
EMULATED_MACHINE: pc
VERSION: 2.2.0-0.0.master.20170413122212
GATEWAY: 10.35.1.254
ISCSI_PORT: 3260
ISCSI_TARGET: iqn.2017-10.com.redhat.tlv:sla-leonard
LUN_ID: 36001405879c330daed74eae8ec28a237
NFS_STORAGE: true
ISCSI_STORAGE: false
ISCSI_USERNAME: username
ISCSI_PASSWORD: password
DOMAIN_TYPE: nfs3
STORAGE: shablul.eng.lab.tlv.redhat.com:/exports/multipass/export/images/rnd/etokar/sansa/he/exports/multipass/export/images/rnd/etokar/sansa/he
