---
- name: Obtain SSO token using username/password credentials
  environment:
    OVIRT_URL: https://{{ FQDN }}/ovirt-engine/api
    OVIRT_USERNAME: admin@internal
    OVIRT_PASSWORD: "{{ ADMIN_PASSWORD }}"
  ovirt_auth:
    insecure: true
  register: ovirt_sso_auth
  until: ovirt_sso_auth is succeeded
  retries: 50
  delay: 10
