---
- name: Create target VM
  hosts: localhost
  connection: local
  vars:
    he_create_target_vm: true
  roles:
    - role: oVirt.hosted-engine-setup
  tags: always

- name: Remote engine VM tasks
  hosts: engine
  vars:
    he_engine_vm_configuration: true
  roles:
    - role: oVirt.hosted-engine-setup
  tags: always

- name: Final setup tasks
  hosts: localhost
  connection: local
  vars:
    he_final_tasks: true
  roles:
    - role: oVirt.hosted-engine-setup
  tags: always