---
- name: Create hosted engine local vm
  hosts: localhost
  connection: local
  tasks:
  - name: Obtain SSO token with using username/password credentials
    ovirt_auth:
      url: https://{{ FQDN }}/ovirt-engine/api
      username: admin@internal
      insecure: true
      password: "{{ ADMIN_PASSWORD }}"
    register: ovirt_sso_auth
    until: ovirt_sso_auth|succeeded
    retries: 50
    delay: 10
  - name: Fetch host facts
    ovirt_hosts_facts:
      pattern: name={{ HOST_NAME }}
      auth: "{{ ovirt_sso_auth.ansible_facts.ovirt_auth }}"
    register: host_result
    until: host_result and 'ansible_facts' in host_result and 'ovirt_hosts' in host_result.ansible_facts and host_result.ansible_facts.ovirt_hosts|length >= 1 and 'up' in host_result.ansible_facts.ovirt_hosts[0].status
    retries: 50
    delay: 10
  - debug: var=host_result
  - name: Fetch cluster id
    set_fact: cluster_id="{{ host_result.ansible_facts.ovirt_hosts[0].cluster.id }}"
  - name: Fetch cluster facts
    ovirt_cluster_facts:
      auth: "{{ ovirt_sso_auth.ansible_facts.ovirt_auth }}"
    register: cluster_facts
  - debug: var=cluster_facts
  - name: Fetch datacenter facts
    ovirt_datacenter_facts:
      auth: "{{ ovirt_sso_auth.ansible_facts.ovirt_auth }}"
    register: datacenter_facts
  - debug: var=datacenter_facts
  - name: Fetch datacenter id
    set_fact: datacenter_id="{{ cluster_facts.ansible_facts.ovirt_clusters|json_query(\"[?id=='" + cluster_id + "'].data_center.id\")|first }}"
  - name: Fetch datacenter_name
    set_fact: datacenter_name="{{ datacenter_facts.ansible_facts.ovirt_datacenters|json_query(\"[?id=='" + datacenter_id + "'].name\")|first }}"
  - name: Add nfs storage domain
    ovirt_storage_domains:
      name: "{{ STORAGE_DOMAIN_NAME }}"
      host: "{{ HOST_NAME }}"
      data_center: "{{ datacenter_name }}"
      wait: True
      nfs:
        address: "{{ STORAGE_DOMAIN_ADDR }}"
        path: "{{ STORAGE_DOMAIN_PATH }}"
#       mount_options: "{{ MOUNT_OPTIONS }}"  # TODO: investigate 404 error
        version: "{{ NFS_VERSION }}"
      auth: "{{ ovirt_sso_auth.ansible_facts.ovirt_auth }}"
    register: otopi_storage_domain_details
    when: DOMAIN_TYPE == "nfs"
  - name: Add iSCSI storage domain
    ovirt_storage_domains:
      name: "{{ STORAGE_DOMAIN_NAME }}"
      host: "{{ HOST_NAME }}"
      data_center: "{{ datacenter_name }}"
      wait: True
      iscsi:
        address: "{{ STORAGE_DOMAIN_ADDR }}"
        port: "{{ ISCSI_PORT }}"
        target: "{{ ISCSI_TARGET }}"
        lun_id: "{{ LUN_ID }}"
        username: "{{ ISCSI_USERNAME }}"
        password: "{{ ISCSI_PASSWORD }}"
      auth: "{{ ovirt_sso_auth.ansible_facts.ovirt_auth }}"
    register: otopi_storage_domain_details
    when: DOMAIN_TYPE == "iscsi"
  - debug: var=otopi_storage_domain_details
...
