---
- name: iSCSI related tasks
  hosts: localhost
  connection: local
  tasks:
  - include_tasks: auth_sso.yml
  - name: iSCSI discover
    ovirt_hosts:
      name: "{{ HOST_NAME }}"
      state: iscsidiscover
      iscsi:
        username: "{{ ISCSI_USERNAME }}"
        password: "{{ ISCSI_PASSWORD }}"
        address: "{{ ISCSI_PORTAL_ADDR }}"
        port: "{{ ISCSI_PORTAL_PORT }}"
      auth: "{{ ovirt_auth }}"
    register: otopi_iscsi_targets
  - debug: var=otopi_iscsi_targets
...
