---
- name: iSCSI related tasks
  hosts: localhost
  connection: local
  tasks:
  - include_tasks: auth_sso.yml
  - name: iSCSI login
    ovirt_hosts:
      name: "{{ HOST_NAME }}"
      state: iscsilogin
      iscsi:
        username: "{{ ISCSI_USERNAME }}"
        password: "{{ ISCSI_PASSWORD }}"
        address: "{{ ISCSI_PORTAL_ADDR }}"
        port: "{{ ISCSI_PORTAL_PORT }}"
        target: "{{ ISCSI_TARGET }}"
      auth: "{{ ovirt_sso_auth.ansible_facts.ovirt_auth }}"
  - name: Get iSCSI LUNs
    ovirt_host_storage_facts:
      host: "{{ HOST_NAME }}"
      iscsi:
        username: "{{ ISCSI_USERNAME }}"
        password: "{{ ISCSI_PASSWORD }}"
        address: "{{ ISCSI_PORTAL_ADDR }}"
        port: "{{ ISCSI_PORTAL_PORT }}"
        target: "{{ ISCSI_TARGET }}"
      auth: "{{ ovirt_sso_auth.ansible_facts.ovirt_auth }}"
    register: otopi_iscsi_devices
  - debug: var=otopi_iscsi_devices
...
