---
- name: iSCSI related tasks
  hosts: localhost
  connection: local
  tasks:
  - name: iSCSI login
    ovirt_hosts:
      name: "{{ HOST_NAME }}"
      state: iscsilogin
      iscsi:
        username: "{{ ISCSI_USERNAME }}"
        password: "{{ ISCSI_PASSWORD }}"
        address: "{{ ISCSI_PORTAL_ADDR }}"
        port: "{{ ISCSI_PORTAL_PORT }}"
        target: "{{ ISCSI_TARGET }}"
      auth:
        username: admin@internal
        password: "{{ ADMIN_PASSWORD }}"
        url: https://{{ FQDN }}/ovirt-engine/api
        insecure: true
  - name: Get iSCSI LUNs
    ovirt_host_storage_facts:
      host: "{{ HOST_NAME }}"
      iscsi:
        username: "{{ ISCSI_USERNAME }}"
        password: "{{ ISCSI_PASSWORD }}"
        address: "{{ ISCSI_PORTAL_ADDR }}"
        port: "{{ ISCSI_PORTAL_PORT }}"
        target: "{{ ISCSI_TARGET }}"
      auth:
        username: admin@internal
        password: "{{ ADMIN_PASSWORD }}"
        url: https://{{ FQDN }}/ovirt-engine/api
        insecure: true
    register: otopi_iscsi_devices
  - debug: var=otopi_iscsi_devices
...
